# Generated by Django 4.2.6 on 2023-11-28 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logincals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='color',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
