# Generated by Django 4.2.7 on 2023-11-29 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eclass', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classlist',
            name='day1',
            field=models.CharField(blank=True, choices=[('월', 'Monday'), ('화', 'Tuesday'), ('수', 'Wednesday'), ('목', 'Thursday'), ('금', 'Friday'), ('토', 'Saturday'), ('일', 'Sunday')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='classlist',
            name='day2',
            field=models.CharField(blank=True, choices=[('월', 'Monday'), ('화', 'Tuesday'), ('수', 'Wednesday'), ('목', 'Thursday'), ('금', 'Friday'), ('토', 'Saturday'), ('일', 'Sunday')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='classlist',
            name='endtime1',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='classlist',
            name='endtime2',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='classlist',
            name='starttime1',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='classlist',
            name='starttime2',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
