# Generated by Django 4.2.6 on 2023-10-31 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eclass', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='classlist',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('professor', models.CharField(max_length=20)),
                ('day1', models.CharField(blank=True, max_length=2, null=True)),
                ('day2', models.CharField(blank=True, max_length=2, null=True)),
                ('starttime1', models.CharField(blank=True, max_length=20, null=True)),
                ('endtime1', models.CharField(blank=True, max_length=20, null=True)),
                ('starttime2', models.CharField(blank=True, max_length=20, null=True)),
                ('endtime2', models.CharField(blank=True, max_length=20, null=True)),
                ('place', models.CharField(max_length=100)),
                ('major', models.CharField(max_length=50)),
            ],
        ),
    ]
