# Generated by Django 4.2.6 on 2023-11-01 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eclass', '0002_classlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSVFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='csv_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
