# Generated by Django 4.2.6 on 2023-11-14 06:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eclass', '0005_alter_userprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserClasslist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='CSVFile',
        ),
        migrations.AlterField(
            model_name='classlist',
            name='id',
            field=models.AutoField(primary_key=True, serialize=True),
        ),
        migrations.AlterField(
            model_name='classlist',
            name='place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userclasslist',
            name='userclass',
            field=models.ManyToManyField(to='eclass.classlist'),
        ),
    ]
