# Generated by Django 4.2.7 on 2023-11-14 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eclass', '0006_userclasslist_delete_csvfile_alter_classlist_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSVFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='csv_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='classlist',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='classlist',
            name='place',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='UserClasslist',
        ),
    ]
