# Generated by Django 4.2.7 on 2023-11-16 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eclass', '0009_alter_userclasslist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classlist',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
