# Generated by Django 4.2.6 on 2023-12-03 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eclass', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClassPage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eclass.userclasslist')),
                ('ClassUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eclass.userprofile')),
            ],
        ),
    ]
